sudo: required
language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
    - .cache
install:
  - npm install
script:
  - npm run compile
  - npm run buidlerevm
  - sleep 5
  - npm run test
  #- npm run coverage && cat coverage/lcov.info | coveralls
  - npm run stop
